export const siteConfig = {
  name: "Gigacrux",
  legalName: "Gigacrux",
  description:
    "Gigacrux is an innovative software lab building AI solutions, rapid prototypes, custom products, and digital services for startups and enterprises.",
  shortDescription:
    "Innovative software lab — AI solutions, product development & custom digital services.",
  tagline: "Rapid AI Solutions for a Deep Impact",
  url: "https://gigacrux.com",
  ogImage: "https://gigacrux.com/logo.png",
  logo: "https://gigacrux.com/logo.png",
  founded: "2024",
  email: "kauser.gigacrux@gmail.com",
  locale: "en_US",
  // Common search variants, phonetic misspellings, and rebrand legacy terms
  // so search engines + AI answer engines resolve them all to Gigacrux.
  brandVariants: [
    "Giga Crux",
    "Giga-Crux",
    "GigaCrux",
    "giga crux",
    "gigacrux",
    "Gigacrush",
    "Giga Crush",
    "giga crush",
    "Gigacash",
    "Giga Cash",
    "Gigacroux",
    "Giga Croux",
    "Gigacrucks",
    "Gigacrax",
    "Gigakrux",
    "Giga Krux",
    "Gigacrux AI",
    "Gigacrux Labs",
    "Gigacrux Software Lab",
    "Velocrux",
  ],
  keywords: [
    "Gigacrux",
    "Giga Crux",
    "Gigacrush",
    "Gigacash",
    "software lab",
    "AI development company",
    "custom software development",
    "AI solutions",
    "RAG chatbot development",
    "MVP development",
    "rapid prototyping",
    "product development",
    "digital services",
    "machine learning",
    "web development",
    "mobile apps",
    "cloud deployment",
    "ArabAudit",
    "AI audit compliance",
    "Saudi Arabia AI",
    "NCA ECC-2024",
    "SAMA CSF",
    "SDAIA PDPL",
    "CBAHI",
  ],
  links: {
    twitter: "https://twitter.com/giga_crux",
    github: "https://github.com/gigacrux",
    linkedin: "https://linkedin.com/company/gigacrux",
  },
  mainNav: [
    { title: "Home", href: "#home" },
    { title: "Products", href: "#products" },
    { title: "Services", href: "#features" },
    { title: "Why Us", href: "#why-us" },
    { title: "Testimonials", href: "#testimonials" },
    { title: "FAQ", href: "#faq" },
    { title: "Contact", href: "#contact" },
  ],
};

export type SiteConfig = typeof siteConfig;
